### ISSUE TITLE
Suggestion to enhance the documentation for arm operations

### ISSUE THREAD

**Issue by oceank** [nasa/ow_simulator#117]
It is great to see that a well-written documentation for many perspectives of ow_simulator has been added into the branch melodic-devel. I suggest to also enhance the documentation for arm operations (e.g., guarded_move, grind and dig_linear), which could help users of ow_simulator in designing and developing their autonomy module. As for the documentation of an arm operation, say guarded_move, a simple description of the operation and its valid parameter range, is highly useful for understanding the capability of the modeled lander in ow_simulator, exploring possible scenarios around and designing an autonomy module for the lander.

Below is the discovered information for guarded_move and grind operations after playing them with multiple parameter settings, which is helpful for developing the autonomy module for the excavation scenario. Hopefully, it could be useful for other users.

## **guarded_move**
Parameters: target_x, target_y, target_z, direction_x=0, direction_y=0, direction_z, search_distance
**Description**: **guarded_move** uses the back of the scoop to search for the ground position (the actual z coordinate) by following the z-axis direction from (target_x, target_y, target_z) to (target_x, target_y, target_z-search_distance).
**Valid Area for (target_x, target_y)** is the area in front of the arm and surrounded by green lines in the figure below, where the blue dot (1, 0) represent the origin of the arm (not the origin the xy-coordinate system). The unit of the labeled numbers is meter.
![reachable_area_by_guarded_move_operation](https://user-images.githubusercontent.com/5262552/117749608-10592380-b1e0-11eb-8d36-c25c3285c362.png)

## **grind**
Parameters: x_start, y_start, depth, length, ground_position, parallel
**Description**: **grind** operation moves in a line by starting from the start point A (x_start, y_start) and then following the same direction as that of from the arm's origin (1, 0) to the start point A.

**Comment by Samahu** [comment]
@oceank thanks for the notes, we will see were this can fit into our documentation and add a section about it.

**Comment by Samahu** [comment]
Closing this as the size and shape of workspace is very much dependent on the details of the terrain and lander pose.
