### ISSUE TITLE
Build Issues with Release 8

### ISSUE THREAD

**Issue by ashishgoel87** [nasa/ow_simulator#128]
Seems like there is some issue with the power module and a specific file called PrognoserFactory.h. Please let me know if I am missing a step

ashish@ashishVM2:~/Software/oceanwaters_ws$ catkin build
--------------------------------------------------------------------------
Profile:                     default
Extending:          [cached] /home/ashish/catkin_ws/devel:/opt/ros/melodic
Workspace:                   /home/ashish/Software/oceanwaters_ws
--------------------------------------------------------------------------
Build Space:        [exists] /home/ashish/Software/oceanwaters_ws/build
Devel Space:        [exists] /home/ashish/Software/oceanwaters_ws/devel
Install Space:      [unused] /home/ashish/Software/oceanwaters_ws/install
Log Space:          [exists] /home/ashish/Software/oceanwaters_ws/logs
Source Space:       [exists] /home/ashish/Software/oceanwaters_ws/src
DESTDIR:            [unused] None
--------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
--------------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
--------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
--------------------------------------------------------------------------
Workspace configuration appears valid.
--------------------------------------------------------------------------
[build] Found '15' packages in 0.0 seconds.                                                                                                                                                                
[build] Updating package table.                                                                                                                                                                            
Starting  >>> irg_gazebo_plugins                                                                                                                                                                           
Starting  >>> irg_spice                                                                                                                                                                                    
Starting  >>> irg_tools                                                                                                                                                                                    
Starting  >>> ow                                                                                                                                                                                           
Finished  <<< irg_tools                              [ 0.6 seconds ]                                                                                                                                       
Starting  >>> ow_bag_recorder                                                                                                                                                                              
Finished  <<< ow                                     [ 0.5 seconds ]                                                                                                                                       
Starting  >>> ow_dynamic_terrain                                                                                                                                                                           
Finished  <<< irg_spice                              [ 0.5 seconds ]                                                                                                                                       
Starting  >>> ow_europa                                                                                                                                                                                    
Finished  <<< ow_bag_recorder                        [ 1.6 seconds ]                                                                                                                                       
Finished  <<< ow_europa                              [ 0.8 seconds ]                                                                                                                                       
Starting  >>> ow_gazebo_plugins                                                                                                                                                                            
Starting  >>> ow_lander                                                                                                                                                                                    
Finished  <<< ow_dynamic_terrain                     [ 1.7 seconds ]                                                                                                                                       
Starting  >>> ow_testbed                                                                                                                                                                                   
Finished  <<< ow_gazebo_plugins                      [ 0.9 seconds ]                                                                                                                                       
Starting  >>> irg_planetary_ephemeris                                                                                                                                                                      
Finished  <<< ow_testbed                             [ 0.7 seconds ]                                                                                                                                       
___________________________________________________________________________________________________________________________________________________________________________________________________________
Warnings   << irg_gazebo_plugins:check /home/ashish/Software/oceanwaters_ws/logs/irg_gazebo_plugins/build.check.002.log                                                                                    
CMake Warning (dev) at /usr/share/cmake-3.10/Modules/FindBoost.cmake:911 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "chrono" will no longer be dereferenced when the
  policy is set to NEW.  Since the policy is not set the OLD behavior will be
  used.
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  /usr/share/OGRE/cmake/modules/FindOGRE.cmake:318 (find_package)
  /usr/lib/x86_64-linux-gnu/cmake/gazebo/gazebo-config.cmake:175 (find_package)
  CMakeLists.txt:14 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

cd /home/ashish/Software/oceanwaters_ws/build/irg_gazebo_plugins; catkin build --get-env irg_gazebo_plugins | catkin env -si  /usr/bin/make cmake_check_build_system; cd -
...........................................................................................................................................................................................................
Finished  <<< irg_planetary_ephemeris                [ 0.8 seconds ]                                                                                                                                       
Finished  <<< ow_lander                              [ 6.0 seconds ]                                                                                                                                       
Starting  >>> ow_faults                                                                                                                                                                                    
Finished  <<< ow_faults                              [ 1.2 seconds ]                                                                                                                                       
Starting  >>> ow_autonomy                                                                                                                                                                                  
Starting  >>> ow_power_system                                                                                                                                                                              
___________________________________________________________________________________________________________________________________________________________________________________________________________
Errors     << ow_power_system:make /home/ashish/Software/oceanwaters_ws/logs/ow_power_system/build.make.002.log                                                                                            
In file included from /home/ashish/Software/oceanwaters_ws/src/ow_simulator/ow_power_system/src/power_system_node.cpp:11:
/home/ashish/Software/oceanwaters_ws/src/ow_simulator/ow_power_system/include/power_system_node.h:9:10: fatal error: PrognoserFactory.h: No such file or directory
    9 | #include <PrognoserFactory.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/power_system_node.dir/src/power_system_node.cpp.o] Error 1
make[1]: *** [CMakeFiles/power_system_node.dir/all] Error 2
make: *** [all] Error 2
cd /home/ashish/Software/oceanwaters_ws/build/ow_power_system; catkin build --get-env ow_power_system | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...........................................................................................................................................................................................................
Failed     << ow_power_system:make                   [ Exited with code 2 ]                                                                                                                                
Failed    <<< ow_power_system                        [ 1.5 seconds ]                                                                                                                                       
Abandoned <<< ow_ephemeris                           [ Unrelated job failed ]                                                                                                                              
Finished  <<< irg_gazebo_plugins                     [ 56.6 seconds ]                                                                                                                                      
___________________________________________________________________________________________________________________________________________________________________________________________________________
Errors     << ow_autonomy:make /home/ashish/Software/oceanwaters_ws/logs/ow_autonomy/build.make.003.log                                                                                                    
Error: /home/ashish/Software/oceanwaters_ws/src/ow_autonomy/src/plans/ReferenceMission2.ple line 318:9 mismatched input ';' expecting RBRACE in action
Error: /home/ashish/Software/oceanwaters_ws/src/ow_autonomy/src/plans/ReferenceMission2.ple line 322:0 extraneous input '}' expecting EOF in block
Error: Standard Plexil compilation of  failed.
Error copying file (if different) from "/home/ashish/Software/oceanwaters_ws/build/ow_autonomy/src/plans/ReferenceMission2.plx" to "/home/ashish/Software/oceanwaters_ws/devel/.private/ow_autonomy/etc/plexil/ReferenceMission2.plx".
make[2]: *** [PLEXILC_ReferenceMission2.plx] Error 1
make[1]: *** [src/plans/CMakeFiles/PLEXILC_ReferenceMission2.plx.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
cd /home/ashish/Software/oceanwaters_ws/build/ow_autonomy; catkin build --get-env ow_autonomy | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...........................................................................................................................................................................................................
Failed     << ow_autonomy:make                       [ Exited with code 2 ]                                                                                                                                
Failed    <<< ow_autonomy                            [ 1 minute and 17.0 seconds ]                                                                                                                         
[build] Summary: 12 of 15 packages succeeded.                                                                                                                                                              
[build]   Ignored:   None.                                                                                                                                                                                 
[build]   Warnings:  1 packages succeeded with warnings.                                                                                                                                                   
[build]   Abandoned: 1 packages were abandoned.                                                                                                                                                            
[build]   Failed:    2 packages failed.                                                                                                                                                                    
[build] Runtime: 2 minutes and 7.3 seconds total.

**Comment by mogumbo** [comment]
Hi Ashish. Release 8 has a new prerequisite called GSAP. You can find setup instructions for GSAP here: https://github.com/nasa/ow_simulator/blob/master/oceanwaters/doc/setup_dev_env.md

**Comment by kmdalal** [comment]
And I've just added a note on the front page that this is a new requirement.

**Comment by ashishgoel87** [comment]
I have the same error, even after building GSAP. Do I have to link it or install it as a system library?

**Comment by kmdalal** [comment]
Sorry, I should have looked at the error message, which is in ow_autonomy.  This is a known problem, fixed by updating your PLEXIL installation:

1. cd $PLEXIL_HOME
2. git branch   (insure that you are on branch releases/plexil-4)
3. git pull    (a small update should come in)
4. make squeaky-clean
5. make

Then retry the 'catkin build'.  
I'm adding a note to the release notes that PLEXIL should be updated.

**Comment by ashishgoel87** [comment]
Sorry, I should have clarified, I fixed that. The issue is still with the power module

--------------------------------------------------------------------------
Profile:                     default
Extending:          [cached] /home/ashish/catkin_ws/devel:/opt/ros/melodic
Workspace:                   /home/ashish/Software/oceanwaters_ws
--------------------------------------------------------------------------
Build Space:        [exists] /home/ashish/Software/oceanwaters_ws/build
Devel Space:        [exists] /home/ashish/Software/oceanwaters_ws/devel
Install Space:      [unused] /home/ashish/Software/oceanwaters_ws/install
Log Space:          [exists] /home/ashish/Software/oceanwaters_ws/logs
Source Space:       [exists] /home/ashish/Software/oceanwaters_ws/src
DESTDIR:            [unused] None
--------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
--------------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
--------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
--------------------------------------------------------------------------
Workspace configuration appears valid.
--------------------------------------------------------------------------
[build] Found '15' packages in 0.0 seconds.                                                         
[build] Package table is up to date.                                                                
Starting  >>> irg_gazebo_plugins                                                                    
Starting  >>> irg_spice                                                                             
Starting  >>> irg_tools                                                                             
Starting  >>> ow                                                                                    
Finished  <<< irg_spice                              [ 0.5 seconds ]                                
Starting  >>> ow_bag_recorder                                                                       
Finished  <<< irg_tools                              [ 0.7 seconds ]                                
Finished  <<< ow                                     [ 0.8 seconds ]                                
Starting  >>> ow_dynamic_terrain                                                                    
Finished  <<< irg_gazebo_plugins                     [ 2.1 seconds ]                                
Starting  >>> ow_europa                                                                             
Starting  >>> ow_gazebo_plugins                                                                     
Finished  <<< ow_bag_recorder                        [ 1.8 seconds ]                                
Starting  >>> ow_lander                                                                             
Finished  <<< ow_europa                              [ 0.7 seconds ]                                
Starting  >>> ow_testbed                                                                            
Finished  <<< ow_gazebo_plugins                      [ 0.7 seconds ]                                
Starting  >>> irg_planetary_ephemeris                                                               
Finished  <<< ow_dynamic_terrain                     [ 2.2 seconds ]                                
Starting  >>> ow_ephemeris                                                                          
Finished  <<< ow_testbed                             [ 0.6 seconds ]                                
Finished  <<< irg_planetary_ephemeris                [ 0.8 seconds ]                                
Finished  <<< ow_ephemeris                           [ 0.9 seconds ]                                
Finished  <<< ow_lander                              [ 3.2 seconds ]                                
Starting  >>> ow_faults                                                                             
Finished  <<< ow_faults                              [ 0.7 seconds ]                                
Starting  >>> ow_autonomy                                                                           
Starting  >>> ow_power_system                                                                       
____________________________________________________________________________________________________
Errors     << ow_power_system:make /home/ashish/Software/oceanwaters_ws/logs/ow_power_system/build.make.001.log
In file included from /home/ashish/Software/oceanwaters_ws/src/ow_simulator/ow_power_system/src/power_system_node.cpp:11:
/home/ashish/Software/oceanwaters_ws/src/ow_simulator/ow_power_system/include/power_system_node.h:9:10: fatal error: PrognoserFactory.h: No such file or directory
    9 | #include <PrognoserFactory.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/power_system_node.dir/src/power_system_node.cpp.o] Error 1
make[1]: *** [CMakeFiles/power_system_node.dir/all] Error 2
make: *** [all] Error 2
cd /home/ashish/Software/oceanwaters_ws/build/ow_power_system; catkin build --get-env ow_power_system | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
....................................................................................................
Failed     << ow_power_system:make                   [ Exited with code 2 ]                         
Failed    <<< ow_power_system                        [ 1.8 seconds ]                                
Finished  <<< ow_autonomy                            [ 1 minute and 19.7 seconds ]                  
[build] Summary: 14 of 15 packages succeeded.                                                       
[build]   Ignored:   None.                                                                          
[build]   Warnings:  None.                                                                          
[build]   Abandoned: None.                                                                          
[build]   Failed:    1 packages failed.                                                             
[build] Runtime: 1 minute and 28.5 seconds total.

**Comment by kmdalal** [comment]
Is your GSAP_HOME environment variable set, and pointing to the GSAP installation directory?

**Comment by ashishgoel87** [comment]
Thanks Mike. Just cleaning everything and building from scratch made it work. Thanks!
