### ISSUE TITLE
Error when invoking DigLinear Action

### ISSUE THREAD

**Issue by ashishgoel87** [nasa/ow_simulator#133]
I am able to execute the Unstow and Stow actions but when I try to execute the DigLinear action, I get the following error

```
[ERROR] [1623277047.758308, 1916525461.010000]: Exception in your execute callback: 'bool' object has no attribute 'joint_trajectory'
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/actionlib/simple_action_server.py", line 289, in executeLoop
    self.execute_callback(goal)
  File "/home/ashish/Software/oceanwaters_ws/src/ow_simulator/ow_lander/scripts/dig_linear_action_server.py", line 80, in on_DigLinear_action
    plan = self._update_motion(goal)
  File "/home/ashish/Software/oceanwaters_ws/src/ow_simulator/ow_lander/scripts/dig_linear_action_server.py", line 68, in _update_motion
    self._interface.moveit_fk, goal)
  File "/home/ashish/Software/oceanwaters_ws/src/ow_simulator/ow_lander/scripts/action_dig_linear.py", line 170, in dig_linear
    if len(plan_a.joint_trajectory.points) == 0:  # If no plan found, abort
AttributeError: 'bool' object has no attribute 'joint_trajectory'
```

Is it due to the inputs I am choosing for x_start, y_start, depth etc. If so, could you please provide a sample set of inputs that would work?

**Comment by anjan1984** [comment]
Thanks for pointing this out. I will take a look at this. The following values worked for us. 

goal.x_start = 1.46    
goal.y_start = 0    
goal.depth = 0.01    
goal.length = 0.1    
goal.ground_position =  -0.155

**Comment by ashishgoel87** [comment]
Thanks Anjan. That worked for me. In general, I think it would be helpful if you provided such sample test inputs for various actions. In this specific case, I didn't know what ground_position is supposed to mean

**Comment by anjan1984** [comment]
Hi Ashish, thanks for your feedback. We will try to define each of the terms more clearly.  In folder ow_simulator/ow_lander/scripts/ you can find a list of action clients to run all the actions. In the client scripts some other values are also provided (commented out) to test the actions clients.

**Comment by kmdalal** [comment]
I think our ARROW user Jianhai Su has made an excellent suggestion along these lines in the other Issue (#117 ).

**Comment by kmdalal** [comment]
Assuming this old issue can be closed.  Please let us know if you still encounter such errors, on any arm operation.
