### ISSUE TITLE
Error while building noetic-devel branch

### ISSUE THREAD

**Issue by pthangeda** [nasa/ow_simulator#188]
Hi everyone,

I am a part of the DRILLAWAY team at University of Illinois Urbana-Champaign and was trying to build [noetic-devel](https://github.com/nasa/ow_simulator/tree/noetic-devel) branch to prepare for the targeted migration to ROS Noetic. Building one of the packages failed as the directory `ow_faults` seems to be missing in this branch. Copying the missing directory from master branch did fix this issue; I just wanted to check if this is the right way to do it or if I should use some other branch to get the Noetic version.

Thanks! 
Pranay

**Comment by mogumbo** [comment]
Hi Pranay,
There's no longer an ow_faults package. Instead we have ow_faults_injection and ow_faults_detection. To build from scratch you will need to check out the noetic-devel branch for ow_simulator and ow_autonomy. There's no noetic-devel branch for ow_europa or irg_open, so you can keep those on melodic-devel. None of this has been properly documented yet.

Also, there's at least one big runtime issue in ow_autonomy that hasn't been fixed for noetic yet: https://github.com/nasa/ow_simulator/pull/187 Once that one is merged I think we'll be ready to give the noetic build a thorough test.

**Comment by pthangeda** [comment]
Thank you so much for the quick response, @mogumbo! I am closing the issue and will wait for the official update on the Noetic release.
