### ISSUE TITLE
No image data published on the corresponding topics (noetic-devel branch)

### ISSUE THREAD

**Issue by pthangeda** [nasa/ow_simulator#201]
I am running the `noetic-devel` branch and it looks like no images are being published in the camera topics. Here are the series of steps to reproduce the error:

Initialize OceanWATERS using the following commands:

```
cd oceanwaters_ws
source devel/setup.bash
roslaunch ow atacama_y1a.launch
```

Check to see if the left camera is publishing any image data:
```
rostopic echo /StereoCamera/left/image_raw
```

The following is a screenshot of the rviz GUI showing that the simulation is active and that no image data is received from the left camera:

![no_image](https://user-images.githubusercontent.com/17803179/144122162-6a029411-0aa6-4f5e-bbd7-a3d814f1260d.png)

Am I doing something wrong or do I have to call a service to enable the cameras?

**Comment by mogumbo** [comment]
You need to trigger the camera to get an image. `rostopic pub -1 /StereoCamera/left/image_trigger std_msgs/Empty`

You can also trigger it using the `Message Publisher` widget in rqt or by selecting `Plugins->Robot Tools->[irg] Image Trigger`

**Comment by Samahu** [comment]
The image below shows how to enable the camera trigger event using the default rqt windows spawned by the simulation:

![image](https://user-images.githubusercontent.com/606033/144141590-107f903d-8bc2-4994-af67-c699f3e39eaf.png)

Note that `/ant_pan_position_controller/command` and `/ant_tilt_position_controller/command` topics were enabled just to give the camera some perspective into the scene but they are not needed to start getting a feed from the camera. You only need to enable `/StereoCamera/left/image_trigger` as @mogumbo pointed out.

**Comment by pthangeda** [comment]
Thank you for the detailed response!
