### ISSUE TITLE
Tutorials still refer to ROS services rather than actions

### ISSUE THREAD

**Issue by ashishgoel-87** [nasa/ow_simulator#211]
It looks like the tutorials are still referring to ROS services rather than ROS actions for invoking different commands. It would be helpful if you added some tutorials for using ROS actions to command the testbed.

Thanks!

**Comment by AstroStucky** [comment]
The tutorials are still specific to only ROS arm services, and we could probably bulk up the tutorial page in general with more procedures to try. 

Though it's not a full tutorial, we do have [a section here on calling ROS arm actions](https://github.com/nasa/ow_simulator/wiki/Lander-Simulation#ros-actions-for-arm). The arguments for which are essentially identical to those for arm services.

**Comment by kmdalal** [comment]
Closing this, since the work needed is captured in our Jira OW-926.
