### ISSUE TITLE
Cmake download_file step refers to a bsp file that does not exist

### ISSUE THREAD

**Issue by mprather** [nasa/ow_simulator#219]
**Commit**: 73b9f3d (from Jan 21, 2022)

In ow_ephemeris/CMakeLists.txt, the following refers to a .bsp file that does not exist at https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/satellites/

```
download_file(
  https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/satellites/sat427.bsp
  f09fb34fc9ec04af4971e4ea097628e5
)
```

**Result**: ow_simulator fails to build with the following report...

```
CMake Error at <path>/src/oceanwaters_ws/src/ow_simulator/ow_ephemeris/CMakeLists.txt:42 (message):

  /home/skipper/src/oceanwaters_ws/src/ow_simulator/ow_ephemeris/data/sat427.bsp
  does not produce the expected md5sum.
```

**Comment by abcouwer-jpl** [comment]
I ran into this and found the missing file in https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/satellites/a_old_versions/ . I changed the link in the CMakeLists.txt and the build succeeded.

**Comment by mprather** [comment]
Another alternative is to simply comment out the step. The build will succeed if the bsp is commented out.

However, I don't think either proposal is the right fix. A folder called "old_version" tells me that it might go away at any point in time and just commenting out the step seems like promising a future break somewhere else.

If this is truly a run-time requirement, then I would suggest the proper fix is the removal of the download from cmake. I shouldn't be able to comment out a build step and still have the build successfully complete.

**Comment by kmdalal** [comment]
Thanks for informing.  This happens once in a while, i.e. ephemeris files get updated and renamed on the JPL server.   Note that this will only impact a first-time clone of the repository (which is when the files are downloaded) and not a clean build.

We have found the replacement file.  Stand by for a patch...

**Comment by kmdalal** [comment]
@mprather , FYI this Saturn ephemeris file is not actually used.  Early on there was a plan to include an Enceladus world but it hasn't happened.  We are living the file in the build for now.

**Comment by Samahu** [comment]
@mprather Hotfix #220 replaced the deprecated ephemeris kernel for Saturn with a more recent one. If you pull the latest from the **master** and re-compile, then the compilation should proceed normally this time. Note if you resorted to using the https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/satellites/a_old_versions/ as @abcouwer-jpl hinted out (which is a valid solution) but you wish to upgrade to the newer kernel (although not currently in use by the simulator) then you should remove the file `sat427.bsp` from the folder `src/ow_simulator/ow_ephemeris/data/`
