### ISSUE TITLE
joint_states and arm_controller/state velocities inconsistent with position

### ISSUE THREAD

**Issue by astako** [nasa/ow_simulator#228]
The velocities from both /joint_states and /arm_controller/state topics appear to be inconsistent with reported positions from those topics.

The plots are the result of executing a deliver sample final motion starting from the default unstowed position. 

This plot shows the position (top subplot) and velocity (bottom subplot) of the joint_state and arm_controller/state actual topics for the shoulder pitch joint:
<img width="401" alt="image" src="https://user-images.githubusercontent.com/102247094/159780865-bbbc92fd-31bf-4c8f-a468-f2ead61601e0.png">

The position is basically a ramp function which should not result in the velocity profile shown in the bottom subplot.

To further illustrate this point, this plot shows the joint_state topic velocity (red trace) and calculated velocity from the joint_states position (back differencing position and dividing by back differencing the time data) for the shoulder pitch joint:
<img width="395" alt="image" src="https://user-images.githubusercontent.com/102247094/159781842-b9ea76c3-0e0f-4110-a805-acaf3c8d194a.png">

This plot is the same thing using the arm_controller/state actual positions and velocities, also for shoulder pitch:
<img width="568" alt="image" src="https://user-images.githubusercontent.com/102247094/159781611-ed123ade-7868-4123-af83-e19b062a0b66.png">
where "calc from actual" refers to the back-differenced actual position.

Clearly, the reported velocities are not at all consistent with the positions. 

This last plot shows the /arm_controller/state actual positions (top subplot) and velocities (bottom subplot) compared to desired:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/102247094/159783406-3ecf5f53-7913-4daf-9111-4c8ba450bdef.png">

This behavior was observed in other joints as well. 

It should be noted that the run was executed using Rviz to move the arm. Similar behavior was also seen when using an RQT service call.

**Comment by Samahu** [comment]
@astako When attempting to re-produce the same results that you have presented, I got totally different plots for the position and velocity of the same joint **shou_pitch** performing the same movement (executing _deliver_sample_ from _unstowed_ state). The relation between the velocity and the position of the joint seems reasonable using the plots that I have produced.

## arm_controller_state (shou_pitch) [unstow -> deliver_sample]
![arm_controller_state_shou_pitch_position_velocity](https://user-images.githubusercontent.com/606033/163069471-5322a362-7e71-4ed1-84b0-e1bf325ae4fd.png)
## joint_states (shou_pitch) [unstow -> deliver_sample]
![joint_state_shou_pitch_position_velocity](https://user-images.githubusercontent.com/606033/163069552-ff7194cd-6142-49d4-8568-e7b9085f9667.png)

Can you double check the process you followed to produce the plots described in this ticket.

**Comment by astako** [comment]
@Samahu: 

It looks like your plots have some extra motion that are not in mine. Did you start from an unstowed position?
But even in your plot I see evidence of velocity mismatch from position. The position around index 500 is clearly a ramp, but the velocity is not even close to a square wave until well past index 500. That's the kind of mismatch I was talking about.

This is the process I followed:

- from stowed arm position, unstowed arm using RQT service call (wait for arm to reach unstowed position)
- start ROS bag record for select topics 
- In RVIZ GUI, set goal state to arm_deliver_final and press "Plan & Execute" 
- wait for arm to reach final position and stop recording

I don't have an easy way to visualize rosbag topics so I dump the rosbag into webviz to plot and then I capture what is plotted to a csv file which I then bring into Matlab for more plotting and analysis capability. The plots in #228 were generated in Matlab from a csv capture from Webviz.  In case I mixed up the indexes, I'm showing below   a screenshot of the webviz plot of the shoulder pitch joint  arm _controller topic values from the rosbag:
![image](https://user-images.githubusercontent.com/102247094/163241718-3b5f136e-5f19-4acf-b258-920da2839245.png)

and here are the joint_states for shoulder_pitch:
<img width="1580" alt="image" src="https://user-images.githubusercontent.com/102247094/163242034-b32778bc-47a9-449d-bf6a-605b7e350915.png">

They look the same as Matlab.

**Comment by Samahu** [comment]
@astako I cannot comment much on why your plots looks different than mine, but yes I invoked the "deliver_sample" activity from an "unstowed" position as I clearly stated. Is it possible that you are monitoring a different joint?

With regard to your second point, in the following plot I used the reported velocity to compute the expected displacement:

![joint_state_shou_pitch_position_velocity_computed](https://user-images.githubusercontent.com/606033/163464466-edf6a8b6-8cc1-45ce-be52-0b806c8d75fa.png)

I would have to agree that the computed position does not line up very well with the reported position. I am still try to gather some insights on why this is the case.

**Comment by astako** [comment]
I may have an idea of why the plots look different. I re-ran the case again (after upgrading to the latest OW master version) twice.
The first time I used RQT service call deliver_sample
The second time I used  RVIZ -> final goal state -> arm_deliver_final

I noted differences in the visualization (as shown in Rviz). The arm motion in the RQT run was broken up into segments with periods of no motion in between, similar to what I see in your plots.
The Rviz run was all one motion with no stops, which is what my plots suggest. Also, I think even the final position of the scoop was not the same for each run (going from memory in what I saw in sim visualization) but I can probably confirm when I look at the scoop yaw plots.

Yes, the velocity to position mismatches is what I have been talking about. I did it slightly different by taking the numerical derivative of position and comparing it to velocity but the conclusion is the same. Something is not quite right.

I’m going to take a closer look at the two aforementioned runs but at a high level, the

Ksenia Kolcio
Vice President, Okean Solutions, Inc.
E: ***@***.******@***.***>, P: 310.704.6174
***@***.***
MONSID<http://monsid.com/> fault management software

**Comment by Samahu** [comment]
Hi @astako 

On the last plot I shared I made a mistake when converting rostime to seconds, ROS uses nanoseconds for the time but wrongly I multiplied the value by 10e-8 instead of 10e-9.

Here are the updated charts:
| arm_controller/state/desired | arm_controller/state/actual |
| ---------- | ---------- |
|![joint_state_shou_pitch_position_velocity_desired_computed](https://user-images.githubusercontent.com/606033/163485120-6338ed2b-e529-40a9-82ce-e9e44a44da58.png)|![joint_state_shou_pitch_position_velocity_computed](https://user-images.githubusercontent.com/606033/163484711-f7d78755-e71b-4bba-90d9-28b7422ced1c.png)|

On the first plot (desired), you can clearly see that the positions computed based on desired velocity matches exactly the desired position.

On the second plot (actual), While the actual positions and the positions computed using the actual velocity don't fully match they do lineup with a bit of error. This could be attributed to simulated noise in the encoders.

**Comment by astako** [comment]
Hi @Samahu 

Regarding your second plot, even if there is simulated encoder noise, I would expect better matching in actual position because it should be derived from the simulated encoders, which would represent actual velocity. The simulated encoders could also be used as position sensors, which would represent actual position. In that case, the numerical derivative of actual position should result in actual velocity.

**Comment by astako** [comment]
Hi @Samahu 
I want to understand why our plots are so different. How are you commanding the arm? Are you using action scripts?
As I mentioned, I did 2 runs, one using RQT service call deliver_sample and one using Rviz plan and execute with goal state set to arm_deliver_final. The run I did using Rviz looks exactly like what I showed before so I'm certain that my earlier plots are of the shoulder pitch joint. 
Neither of the RQT nor Rviz runs looks like yours. The RQT run does result in a more complicated motion, but unlike yours which is continuous, mine is clearly segmented with quiescent periods in between moves.
Here is the actual position and position calculated from actual velocity for the RQT run:
<img width="527" alt="image" src="https://user-images.githubusercontent.com/102247094/163604257-c51a82f9-322c-4648-8bc8-4f9fe30e5906.png">
The next plot shows velocity calculated from actual position in the 3rd subplot:
<img width="526" alt="image" src="https://user-images.githubusercontent.com/102247094/163604452-7c9747dc-20b1-4e65-9c56-79442f942c7f.png">

The velocity deviation occurs early in the run and then the actual velocity eventually lines up with the velocity calculated from actual position. In that respect, our runs are similar. 

I don't see how the mismatches between actual and computed could be the result of encoder noise. Most simulated sensor noise models are some form of random distribution which is usually  Gaussian. This cannot explain the deviation in the RQT run for the hand yaw joint shown below.
Actual position and position calculated from actual velocity:
<img width="589" alt="image" src="https://user-images.githubusercontent.com/102247094/163607974-b210033f-8f08-4604-bd59-5225f82b1add.png">
The big dip at about 28 seconds into the run does not look like the result of noise.

Here is the actual velocity and velocity calculated from actual position in 3rd subplot:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/102247094/163608124-808de8f7-2f73-4b96-8b1b-b2fac2ca39c7.png">

**Comment by Samahu** [comment]
I typically use ROS Services (RQT or command line) to execute arm activities but they were broken on our current development branch (fix currently in review #235), so I ended up using the action scripts to execute arm activities and generated the plots of that motion (not sure how they could differ).

**Comment by astako** [comment]
To summarize:
Based on our plots it looks like different arm motion results are obtained depending on which of the following are used: 

- ROS services, 
- Rviz plan and execute (from current to goal state), 
- action scripts 

at least for the stating state of unstowed to the end state of deliver sample.
All three methods resulted in velocity/position mismatches over portions of the motion.

Do you agree with this summary?

**Comment by Samahu** [comment]
@astako I am investigating why ROS Services could be different from the ROS Action interface, but with regard to using the RVIZ planning interface what is the current state and the goal state that you used when generating these plots?

**Comment by Samahu** [comment]
Here is a plot that shows the differences between the motion we get when using rosservice vs rosaction:
| arm_controller/state/actual (rosaction) | arm_controller/state/actual (rosservice) |
| ---------- | ---------- |
|![joint_state_shou_pitch_position_velocity_computed](https://user-images.githubusercontent.com/606033/163484711-f7d78755-e71b-4bba-90d9-28b7422ced1c.png)|![arm_controller_state_actual_shou_pitch_rosservice](https://user-images.githubusercontent.com/606033/164070980-5cac6098-8bb3-4af2-97c3-f31e62669438.png)|

The actual position look similar but the velocity and the computed positions look quite different. So I would have to agree on this fact. I don't know why this is the case yet.

**Comment by astako** [comment]
> @astako I am investigating why ROS Services could be different from the ROS Action interface, but with regard to using the RVIZ planning interface what is the current state and the goal state that you used when generating these plots?

current state was unstowed and goal state was set to: arm_deliver_sample

**Comment by astako** [comment]
Regarding the differences between rosservice and rosaction plots, even the actual positions look different as rosaction first goes down then up while rosservice goes up then down.

**Comment by Samahu** [comment]
I don't think in the last released version of **OceanWATERS** that we have `arm_deliver_sample` state, which version of OceanWATERS are you currently testing with?

**Comment by astako** [comment]
I'm running commit be67199e44e406714503a943caadd6bccced5a4e.

**Comment by astako** [comment]
> > @astako I am investigating why ROS Services could be different from the ROS Action interface, but with regard to using the RVIZ planning interface what is the current state and the goal state that you used when generating these plots?
> 
> current state was unstowed and goal state was set to: arm_deliver_sample

Sorry, I missed-typed. goal state was set to: arm_deliver_final

**Comment by Samahu** [comment]
> > > @astako I am investigating why ROS Services could be different from the ROS Action interface, but with regard to using the RVIZ planning interface what is the current state and the goal state that you used when generating these plots?
> > 
> > 
> > current state was unstowed and goal state was set to: arm_deliver_sample
> 
> Sorry, I missed-typed. goal state was set to: arm_deliver_final

Aha! the thing with regard to sample delivery motion is a composite sequence. It is made of 3 segments: [`arm_deliver_staging_1`, `arm_deliver_staging_2`, `arm_deliver_final`]. Both the ros service interface and the ros action execute the segments in order. This explain you are getting different plot for RVIZ.

**Comment by astako** [comment]
ok, so Rviz -> arm_deliver_final directly from unstowed state does not include staging1 and staging2, is that right?
That would explain why there don't appear to be segments in the Rviz case.

But does that explain apparent differences between rosservice and rosaction?
Also, there appear to be differences if you compare my RQT service call plots with your rosservice plots for shoulder pitch joint position and velocity.

**Comment by Samahu** [comment]
> ok, so Rviz -> arm_deliver_final directly from unstowed state does not include staging1 and staging2, is that right?

When using RVIZ the arm will go directly from unstowed to final

> But does that explain apparent differences between rosservice and rosaction? Also, there appear to be differences if you compare my RQT service call plots with your rosservice plots for shoulder pitch joint position and velocity.

I did mention they don't match..and no idea at the moment that why is it the case (needs more investigation).
With regard to the second part of your sentence .. we need to make sure that we are plotting for the same joint.

**Comment by Samahu** [comment]
> Hi @astako
> 
> On the last plot I shared I made a mistake when converting rostime to seconds, ROS uses nanoseconds for the time but wrongly I multiplied the value by 10e-8 instead of 10e-9.
> 
> Here are the updated charts:
> 
> arm_controller/state/desired	arm_controller/state/actual
> ![joint_state_shou_pitch_position_velocity_desired_computed](https://user-images.githubusercontent.com/606033/163485120-6338ed2b-e529-40a9-82ce-e9e44a44da58.png)	![joint_state_shou_pitch_position_velocity_computed](https://user-images.githubusercontent.com/606033/163484711-f7d78755-e71b-4bba-90d9-28b7422ced1c.png)
> On the first plot (desired), you can clearly see that the positions computed based on desired velocity matches exactly the desired position.
> 
> On the second plot (actual), While the actual positions and the positions computed using the actual velocity don't fully match they do lineup with a bit of error. This could be attributed to simulated noise in the encoders.

With regard to the disparity between reported actual position vs getting the position through actual velocity, I asked around and I didn't get good answers but some suggested that this could be a result of inaccuracies in the physics solver (no proof- just speculation).

**Comment by Samahu** [comment]
@astako I did a thorough analysis with regard to the effect of physics solver resolution on the reported values for arm movements, the following table compares the integrated position value at two different settings for the solver:

| Typical Solver Resolution (step-size=0.0025s) | Increased Solver Resolution (step-size=0.001) |
| ---------- | ---------- |
|![image](https://user-images.githubusercontent.com/606033/165425282-b509b906-7546-484b-8e6d-f3c2670637e4.png)|![image](https://user-images.githubusercontent.com/606033/165425336-ec74b176-59f7-48dd-a88a-aedf947b81a9.png)|

When the solver resolution has been increased (by decreasing the step size), the position obtained by integrating the actual velocity seem to better converge with the reported actual position. This allows us to conclude the observed disparity can be mainly attributed to the solver inaccuracy.

With regard to the movement disparity between rosservices and rosaction, since I am leaving OceanWATERS, the team is highly likely would focus on rosaction moving forward and drop support for rosaction. That being the case, it is not necessary to investigate the cause beyond this disparity.

Hopefully this response addresses all the points you have raised as part of this issue.

**Comment by Samahu** [comment]
If you have other concerns please let us know.

**Comment by astako** [comment]
@Samahu Thanks for the analysis. I agree that the solver step size seems to be the driving factor in the actual velocity integration and actual position mismatches.
