### ISSUE TITLE
Ground is detected but GuardedMove failed

### ISSUE THREAD

**Issue by oceank** [nasa/ow_simulator#236]
**Issue Description:**
The execution of [TestGuardedMoves.plp](https://github.com/nasa/ow_autonomy/blob/noetic-devel/ow_plexil/src/plans/TestGuardedMoves.plp) detected the ground but finished in state ABORTED. Similar results were observed when trying GuardedMove library action with a bunch of locations different from these in TestGuardedMoves.plp. The logs given by ow_simulator and ow_plexil are listed below. I am not sure if the issue is due to the testing location or maybe a bug in GuardMove. So, I report the issue here. I also tried to bypass GuardedMove by directly executing Grind action with a fake group position of 0.05. But the execution failed with error messages as listed below. Would you please shed some light on this issue? Thanks!

> [ERROR] [1650855185.132681546, 1916526288.809999943]: grinder/grinder: Unable to sample any valid states for goal tree
> [ WARN] [1650855185.140065468, 1916526288.817500114]: Fail: ABORTED: No motion plan found. No execution attempted.

**Test environment:**
ow_simulator: noetic-devel branch, commit 0dd9264
ow_autonomy: noetic-devel branch, commit 9f11ff3

**Log from ow_simulator:**

> [INFO] [1650856147.288529, 1916527250.310000]: Guarded move activity started
> [INFO] [1650856163.233787, 1916527266.172500]: Ground Detected ? True
> [INFO] [1650856166.142323, 1916527269.155000]: GuardedMove: Failed
> [INFO] [1650856171.145730, 1916527274.160000]: Unstow arm activity started
> [INFO] [1650856179.237542, 1916527282.245000]: Unstow: Succeeded
> [INFO] [1650856179.239519, 1916527282.245000]: Stow arm activity started
> [INFO] [1650856194.056101, 1916527297.052500]: Stow: Succeeded
> [INFO] [1650856437.082947, 1916527539.985000]: Unstow arm activity started
> [INFO] [1650856451.882967, 1916527554.780000]: Unstow: Succeeded
> [INFO] [1650856451.884719, 1916527554.782500]: Guarded move activity started
> [INFO] [1650856465.739521, 1916527568.582500]: **Ground Detected ? True**
> [INFO] [1650856466.307193, 1916527569.075000]: G**uardedMove: Failed**

**Log from ow_plexil:**

> [ INFO] [1650856451.884357508, 1916527554.782500029]: Starting GuardedMove(x=2.00, y=0.00, z=0.30, dir_x=0.00, dir_y=0.00,dir_z=1.00, search_dist=0.50)
> [ INFO] [1650856451.884379359, 1916527554.782500029]: Sending goal to action GuardedMove
> [ INFO] [1650856451.884462455, 1916527554.782500029]: Sent goal to action GuardedMove
> [ INFO] [1650856451.884692571, 1916527554.782500029]: GuardedMove started...
> [ INFO] [1650856466.317612077, 1916527569.207499981]: **GuardedMove finished in state ABORTED**
> [ERROR] [1650856471.317810845, 1916527574.204999924]: PLEXIL: First guarded move failed.
> [ INFO] [1650856471.317874505, 1916527574.204999924]: PLEXIL: TestGuardedMoves plan complete.

**Other locations (Parameters) tried with GuardMove and ended with the same result as above described:**
   - X = 1.64, Y =-0.04, Z = -0.07, DirX = 0.00, DirY = 0.00, DirZ = 1.00, SearchDistance = 0.50
   - X = 1.54, Y = 0.1,   Z = 0.05,  DirX = 0.00, DirY = 0.00, DirZ = 1.00, SearchDistance = 0.3

**Comment by oceank** [comment]
The TestGuardedMoves.plp is able to successfully execute two GuardedMoves actions in a version of **release 8** of OceanWATERS simulator. The output log of ow_plexil is listed below.

**Testing Environment:**
   - ow_simulator: commit 662fea6
   - ow_autonomy: commit 34f36ab 

**Log from ow_plexil:**

> [ INFO] [1650861575.584834215, 1916525214.852499962]: GuardedMove started...
> [ INFO] [1650861605.005199024, 1916525244.250000000]: GuardedMove finished in state SUCCEEDED
> [ INFO] [1650861610.005432861, 1916525249.247499943]: PLEXIL: Found ground (first attempt) at -0.163067802497047
> [ INFO] [1650861610.005578185, 1916525249.247499943]: Sending goal to action Unstow
> [ INFO] [1650861610.005722903, 1916525249.247499943]: Sent goal to action Unstow
> [ INFO] [1650861610.061491718, 1916525249.305000067]: Unstow started...
> [ INFO] [1650861623.222263689, 1916525262.457499981]: Unstow finished in state SUCCEEDED
> [ INFO] [1650861623.222585829, 1916525262.457499981]: Sending goal to action GuardedMove
> [ INFO] [1650861623.222717492, 1916525262.457499981]: Sent goal to action GuardedMove
> [ INFO] [1650861623.250121142, 1916525262.484999895]: GuardedMove started...
> [ INFO] [1650861651.972096837, 1916525291.190000057]: GuardedMove finished in state SUCCEEDED
> [ INFO] [1650861656.972284076, 1916525296.187500000]: PLEXIL: Found ground (second attempt) at -0.168066085566255
> [ INFO] [1650861656.972326768, 1916525296.187500000]: PLEXIL: TestGuardedMoves plan complete.

**Comment by kmdalal** [comment]
Thanks for the detailed report, @oceank.  We have reproduced this problem and are investigating.  I suspect it got introduced in a recent commit to noetic-devel, which is not tested as rigorously as the `master` branch, which should not have this problem.

**Comment by anjan1984** [comment]
@oceank we have merged out changes to the noetic devel branch and it should fix this issue. Do let us know if you still see this issue
