### ISSUE TITLE
x = sin, not cos?

### ISSUE THREAD

**Issue by snoyes** [nasa/ow_simulator#265]
https://github.com/nasa/ow_simulator/blob/c060887739287678c53837a37f55dcc1e44ba787/ow_lander/scripts/activity_grind.py#L80-L81

https://github.com/nasa/ow_simulator/blob/c060887739287678c53837a37f55dcc1e44ba787/ow_lander/scripts/activity_grind.py#L85-L86

https://github.com/nasa/ow_simulator/blob/c060887739287678c53837a37f55dcc1e44ba787/ow_lander/scripts/all_action_trajectories.py#L618-L619

https://github.com/nasa/ow_simulator/blob/c060887739287678c53837a37f55dcc1e44ba787/ow_lander/scripts/all_action_trajectories.py#L624-L625

Are sin and cos switched here for one of the actions - parallel or perpendicular?

**Comment by anjan1984** [comment]
Sin and cos are not switched. the parallel or perpendicular directions are with reference to the lander arm stretching outwards from the lander body and not with reference to the lander body itself.
