### ISSUE TITLE
Feature Request: Starting Time Argument

### ISSUE THREAD

**Issue by gleasonj-lm** [nasa/ow_simulator#318]
I would like to be able to specify a starting time, or an offset, to the oceanwaters simulation to accommodate for different shadow conditions created at different points in Europa's orbit around Jupiter. Ideally, I would like to be able to specify this starting time as an argument to a launch file like I might specify `use_rviz`. However I am not sure that arguments are allowed in the world files. Currently we use a bash script to alter the sim time in the desired world file and then launch.

Is adding a command-line style argument to augment the starting simulation time possible?

**Comment by mogumbo** [comment]
I was about to reply that this is not possible with Gazebo. However, this feature was just added: https://github.com/gazebosim/gazebo-classic/pull/3294 I haven't tried it myself. Also, this is now in the gazebo11 branch but there probably hasn't been a new release of gazebo11 in the past week. In the short term if you want to use it you will need to compile gazebo yourself.

**Comment by kmdalal** [comment]
@gleasonj-lm , this is an old issue and I'm wondering if you've found a solution or workaround?  Did you try the gazebo11 suggestion in the previous comment?

**Comment by kmdalal** [comment]
Closing this issue because it's so old.  I have captured it in our internal Jira OCEANWATER-1213.  Please re-request if this is still needed.
