### ISSUE TITLE
Actual arm does not move (release 7)

### ISSUE THREAD

**Issue by oceank** [nasa/ow_simulator#85]
### Problem Description:
With release 7, the actual arm (in yellow) does not move when calling a service, e.g., /arm/unstow, through rqt. Only the virtual arm (in grey) moves.

### System Info:
Use a physical machine but not a virtual machine
OS: Ubuntu 18.04.1
Linux Kernel: 5.4.0-65-generic
ROS: melodic
Gazebo: 9.16
OceanWater: release 7

### Expected Behavior:
The actual arm will move immediately after the virtual arm finishes its move.

### Observed Behavior:
The actual arm does not move when the virtual arm finishes its move. And the rqt shows the service is successfully done in its response window.

### Steps to Reproduced the issue:
1. Installation of OW: follow the steps in [installing software prerequisites](https://github.com/nasa/ow_simulator/blob/master/oceanwaters/doc/setup_dev_env.md) and then [building OceanWater](https://github.com/nasa/ow_simulator/blob/master/oceanwaters/doc/setup_oceanwaters.md).
2. Start Europa Mission workspace:
```
(enter the ocean water workspace which has 'build' and 'devel' folders created by 'catkin build')
source devel/setup.bash
roslaunch ow europa_terminator_workspace.launch
```
3. In left bottom of rqt window, select the Service Caller
4. In the tab of Service Caller, pick the service ''/arm/unstow" and click Call.

### Logs:
Below is the screenshot when the service '/arm/unstow' is done.
![R7_actual_arm_not_move_unstow](https://user-images.githubusercontent.com/5262552/107410509-6a602500-6adb-11eb-8aec-42ef60b5424d.png)

**Comment by Samahu** [comment]
Hi @oceank,

The yellow (looks orange to me) color indicator represents the GoalState of the arm as shown in the following image from RVIZ.
![image](https://user-images.githubusercontent.com/606033/107417508-88715980-6aca-11eb-91be-e25978feeadd.png)

You will see this get's update when you generate a new GoalState through RVIZ.

**Comment by oceank** [comment]
> en you generate a new GoalState through RVIZ

Hi, @Samahu

So, the actual arm is displayed in grey?

What is the definition of GoalState here? Is it linked to the location where the arm should move to after receiving a service call, like /arm/unstow?

**Comment by Samahu** [comment]
> So, the actual arm is displayed in grey?

Yes
> What is the definition of GoalState here? Is it linked to the location where the arm should move to after receiving a service call, like /arm/unstow?

The GoalState reflects the current selection of goal you made through RVIZ, as illustrated below (note the selection of **arm_unstowed** pose in the _Goal State_ field):
![image](https://user-images.githubusercontent.com/606033/107437791-62f14980-6ae4-11eb-9d07-a479049d3762.png)

**Comment by oceank** [comment]
@Samahu Thanks for the explanation! 

I played with different planning groups in MonitorPlanning panel. "arm" is able to rotate the scoop and joints and move in three dimensions, while "grinder" is similar to "arm" except that it can not directly rotate the scoop. And "limbs" can only rotate the ending joint where the scoop and the grind directly connect to and move joints in only one dimension. It looks like that the functionality of the three Planning Groups, "arm", "grinder" and "limbs", have some overlap. Is the current design promoted by some special scenarios?

**Comment by Samahu** [comment]
> @Samahu Thanks for the explanation!
> 
> I played with different planning groups in MonitorPlanning panel. "arm" is able to rotate the scoop and joints and move in three dimensions, while "grinder" is similar to "arm" except that it can not directly rotate the scoop. And "limbs" can only rotate the ending joint where the scoop and the grind directly connect to and move joints in only one dimension. It looks like that the functionality of the three Planning Groups, "arm", "grinder" and "limbs", have some overlap. Is the current design promoted by some special scenarios?

Yes, they do overlap, these groups mainly differ by the designated end-effector. The three groups were actually needed as a workaround of a known limitation in MoveIT API that prevented us from configuring a different end-effector within a move group chain.
