### ISSUE TITLE
Gazebo client shows a black screen (release 7)

### ISSUE THREAD

**Issue by oceank** [nasa/ow_simulator#86]
### Problem Description:
After launching the workspace of Europa Mission, the Gazebo client is opened but shows a black screen.

### System Info:
Use a physical machine but not a virtual machine
OS: Ubuntu 18.04.1
Linux Kernel: 5.4.0-65-generic
ROS: melodic
Gazebo: 9.16
OceanWater: release 7

### Expected Behavior:
The landscape surrounding the lander will be displayed in the Gazebo client.  

### Observed Behavior:
A black screen is shown in the Gazebo client. But The timing parameters and frame rate are actively changing. And sometimes there is a flash of colors on the screen of the Gazebo client. From the terminal, it is observed that the inexistences of "source frame" and "target frame" are mentioned several times in the error messages. More details are shown in the section of Logs.

### Steps to Reproduced the issue:
1. Installation of OW: follow the steps in [installing software prerequisites](https://github.com/nasa/ow_simulator/blob/master/oceanwaters/doc/setup_dev_env.md) and then [building OceanWater](https://github.com/nasa/ow_simulator/blob/master/oceanwaters/doc/setup_oceanwaters.md).
2. Start Europa Mission workspace:
```
(enter the ocean water workspace which has 'build' and 'devel' folders created by 'catkin build')
source devel/setup.bash
roslaunch ow europa_terminator_workspace.launch
```

### Logs:
Below is the screenshot after the successful launch of Europa Mission workspace.
![OW_Release7_Gazebo_Blackout](https://user-images.githubusercontent.com/5262552/107411807-f757ae00-6adc-11eb-8a9e-de786ab5acb0.png)

Part of standard output from the terminal where the Europa workspace is launched.

> [Msg] Loading heightmap: terminator_workspace
> [Msg] Loading heightmap cache data: /home/jsu/.gazebo/paging/terminator_workspace/gazebo_terrain_00000000.dat
> [Msg] Heightmap loaded. Process took: 0.416375 seconds
> [Err] [msgs.cc:2883] Unrecognized geometry type
> Error [Element.cc:702] Missing element description for [param]
> [Err] [msgs.cc:2883] Unrecognized geometry type
> [INFO] [1612820438.213795, 0.000000]: Calling service /gazebo/set_model_configuration
> [INFO] [1612820438.216813, 0.000000]: Set model configuration status: SetModelConfiguration: success
> [INFO] [1612820438.217708, 0.000000]: Unpausing physics
> [ERROR] [1612820438.223972353, 1916524800.002500057]: CelestialBodyPlugin::OnUpdate - "celestial_body_origin" passed to lookupTransform argument target_frame does not exist. 
> [ERROR] [1612820438.224232592, 1916524800.002500057]: CelestialBodyPlugin::OnUpdate - "celestial_body_origin" passed to lookupTransform argument target_frame does not exist. 
> 
> [ERROR] [1612820439.224565271, 1916524801.000000000]: CelestialBodyPlugin::OnUpdate - "celestial_body_origin" passed to lookupTransform argument target_frame does not exist. 
> [ERROR] [1612820439.224683421, 1916524801.000000000]: CelestialBodyPlugin::OnUpdate - "celestial_body_origin" passed to lookupTransform argument target_frame does not exist. 
> [ERROR] [1612820439.548151, 1916524801.322500]: Failed to load grinder_controller
> [INFO] [1612820439.550236, 1916524801.325000]: Controller Spawner: Loaded controllers: 
> [ERROR] [1612820440.224597778, 1916524802.000000000]: CelestialBodyPlugin::OnUpdate - "sun" passed to lookupTransform argument source_frame does not exist. 
> [ERROR] [1612820440.224850778, 1916524802.000000000]: CelestialBodyPlugin::OnUpdate - "jupiter" passed to lookupTransform argument source_frame does not exist.

**Comment by Samahu** [comment]
Hi @oceank , can you verify that **ros-melodic-joint-trajectory-controller** package is properly installed on your system.
You may try the following command to check:
```bash
dpkg -l | grep ros-melodic-joint-trajectory
```

**Comment by oceank** [comment]
Hi, @Samahu 

Here is the information of ros-melodic-joint-trajectory-controller package in my machine.

**ii  ros-melodic-joint-trajectory-controller      0.17.2-1bionic.20210120.180033                   amd64        Controller for executing joint-space trajectories on a group of joints.**

**Comment by Samahu** [comment]
@oceank two questions:
* Was there any changes made to the simulation code?
* How often do you experience this problem, Is it always or it happens sometime?

Thanks
Ussama

**Comment by oceank** [comment]
> * Was there any changes made to the simulation code?

No change was made to the simulation code. I used the tag: v7.0.1 of ow_simulator. Inside the src folder in the catkin workspace, I linked .rosinstall to ow_simulator/oceanwaters/workspaces/oceanwaters.rosinstall as suggested in the tutorial. While I see oceanwaters_release-7-0.rosinstall and oceanwaters_release-6-0.rosinstall inside ow_simulator/oceanwaters/workspaces/. Should .rosinstall be linked to oceanwaters_release-7-0.rosinstall?

> * How often do you experience this problem, Is it always or it happens sometime?

This issue always happens in my machine.

**Comment by Samahu** [comment]
Linking against `ow_simulator/oceanwaters/workspaces/oceanwaters.rosinstall` is the right way of build the simulation.

**Comment by Samahu** [comment]
The reason I asked about **ros-melodic-joint-trajectory-controller** specifically because the only concerning error in your log is the following two:
```bash
[ERROR] [1612820439.548151, 1916524801.322500]: Failed to load grinder_controller
[INFO] [1612820439.550236, 1916524801.325000]: Controller Spawner: Loaded controllers:
```

In a successful run you should get something like:
```bash
[INFO] [1612901988.209742, 1916524800.280000]: Controller Spawner: Loaded controllers: limbs_controller, grinder_controller
[INFO] [1612901988.232516, 1916524800.302500]: Loading controller: ant_tilt_position_controller
[INFO] [1612901988.254390, 1916524800.322500]: Controller Spawner: Loaded controllers: arm_controller, ant_pan_position_controller, ant_tilt_position_controller
[INFO] [1612901988.259413, 1916524800.327500]: Started controllers: arm_controller, ant_pan_position_controller, ant_tilt_position_controller
```

Can you verify that the following two packages are properly installed on your system:
* ros-melodic-joint-state-controller
* ros-melodic-effort-controllers

**Comment by oceank** [comment]
> Can you verify that the following two packages are properly installed on your system:
> 
> * ros-melodic-joint-state-controller
> * ros-melodic-effort-controllers

Here is the information of the two packages installed on my system.

- ii  ros-melodic-joint-state-controller           0.17.2-1bionic.20210120.180034                   amd64        Controller to publish joint state
- ii  ros-melodic-effort-controllers               0.17.2-1bionic.20210120.180415                   amd64        effort_controllers

**Comment by Samahu** [comment]
@oceank we will try to replicate the problem and get back to you

**Comment by zainhussaini** [comment]
I had the same issue before I updated the graphics drivers. I tested again with the latest versions of ow_simulator and plexil and it displays Gazebo correctly. Below I've listed what I'm using so you can check if this would be applicable:

```
OS: Ubuntu 18.04.5 LTS x86_64
GPU: NVIDIA Quadro RTX 4000 Mobile / Max-Q
GPU Driver: NVIDIA 460.32.03
```

If you are using Ubuntu you can check the graphics driver by going to the "Software & Updates" application and going to the "Additional Drivers" tab. Here make sure you have the correct ones (I'm using nvidia-driver-460)

**Comment by oceank** [comment]
@zainhussaini Thanks! 

My OS is Ubuntu 18.04.1. But my machine does not have a GPU. @Samahu Is the GPU necessary here for visualizing the scene in Gazebo client?

**Comment by Samahu** [comment]
> @zainhussaini Thanks!
> 
> My OS is Ubuntu 18.04.1. But my machine does not have a GPU. @Samahu Is the GPU necessary here for visualizing the scene in Gazebo client?

Yes, it is. We do have listed in the [hardware requirements](https://github.com/nasa/ow_simulator/blob/master/oceanwaters/doc/setup_dev_env.md#hardware) section.

**Comment by Samahu** [comment]
Closing this ticket as a misconfigured or unsupported GPU.
