### ISSUE TITLE
Fail to launch the autonomy node (release 7)

### ISSUE THREAD

**Issue by oceank** [nasa/ow_simulator#87]
### Problem Description:
The launch of the autonomy node complains the error, "unable to load module for adapter type "CheckpointAdapter", which leads the node to be shut down. "CheckpointAdapter" is part of PLEXIL. The PLEXIL used here is from its recent commit 65f74037 with a little tweak to remove "safe_name" renaming. More details are elaborated in the section of Installation of PLEXIL-4.

### System Info:
Use a physical machine but not a virtual machine
OS: Ubuntu 18.04.1
Linux Kernel: 5.4.0-65-generic
ROS: melodic
Gazebo: 9.16
OceanWater: release 7
PLEXIL: releases/plexil-4, commit 65f74037

### Installation of PLEXIL-4:
The build of PLEXIL-4 (tag:2020-11-17, as mentioned in the [software prerequisites]((https://github.com/nasa/ow_simulator/blob/master/oceanwaters/doc/setup_dev_env.md))) fails because it can not find a header file, "Debug.hh", as shown in the figure below. The build failure further causes the build of ow_autonomy to fail. 
![plexil_tag_20201117_build_fails](https://user-images.githubusercontent.com/5262552/107412950-2fabbc00-6ade-11eb-9392-7420f8d4867f.png)

By switching PLEXIL-4 to the commit 65f74037, PLEXIL could be built successfully.
![plexil_commit_65f74037_build_success](https://user-images.githubusercontent.com/5262552/107414974-be213d00-6ae0-11eb-9e5a-d5f7352d5f4f.png)

But the build of ow_autonomy still fails. One example of the build errors is listed here.
> Error copying file (if different) from "/home/jsu/ow_ws/build/ow_autonomy/src/plans/TorqueTest.plx" to "/home/jsu/ow_ws/devel/.private/ow_autonomy/etc/plexil/TorqueTest.plx".

In /home/jsu/ow_ws/build/ow_autonomy/src/plans/, there is a file '(safe_name TorqueTest.plx)', but no file named TorqueTest.plx. The renaming operation comes from the _plexil/scripts/plexilc_ file, there is a compile_one_file() function where the input file name is changed into its 'safe_name' version, as shown below.
```
  381     if [ -n "$specified_output" ]
  382     then
  383         dest="(safe_name "$specified_output")"
  384     else
  385         # TODO: destination directory
  386         dest_dir="${dest_dir:-$(dirname "$1")}"
```

Changing line 383 to the following and rebuilding PLEXIL could solve the above naming issue and make the build of ow_autonomy successful.
``` 
  383         dest = "$specified_output"
```
![rebuild ow_autonomy success](https://user-images.githubusercontent.com/5262552/107415029-d85b1b00-6ae0-11eb-9a38-6d4870723c68.png)

### Expected Behavior:
The autonomy node will be initialized successfully and start interacting with the workspace of Europa Mission. 

### Observed Behavior:
The launch of the autonomy node fails due to the failure to construct adapter type "CheckpointAdapter".

### Steps to Reproduced the issue:
1. Installation of OW: follow the steps in [installing software prerequisites](https://github.com/nasa/ow_simulator/blob/master/oceanwaters/doc/setup_dev_env.md) and then [building OceanWater](https://github.com/nasa/ow_simulator/blob/master/oceanwaters/doc/setup_oceanwaters.md).
2. Launch Europa Mission workspace:
```
(enter the ocean water workspace which has 'build' and 'devel' folders created by 'catkin build')
source devel/setup.bash
roslaunch ow europa_terminator_workspace.launch
```
3. Launch the autonomy node in another terminal
```
(enter the ocean water workspace which has 'build' and 'devel' folders created by 'catkin build')
source devel/setup.bash
roslaunch ow_autonomy autonomy_node.launch
```

### Logs:
The standard output from the terminal where the launch command of the autonomy node is issued.

> WARNING: AdapterFactory.cc:114: AdapterFactory: unable to load module for adapter type "CheckpointAdapter"
> WARNING: AdapterConfiguration.cc:604: constructInterfaces: failed to construct adapter type "CheckpointAdapter"
> [ERROR] [1612828487.161218256]: Interface initialization failed
> [ERROR] [1612828487.161254988]: plexilInitializeInterfaces failed
> [ERROR] [1612828487.161266293]: Could not initialize OW executive, shutting down.

**Comment by kmdalal** [comment]
Good catch!  The actual fix was adding a missing '$' in "(safe_name ...)".  Update your releases/plexil-4 branch, which is now frozen except for bugs reported against this branch.

**Comment by oceank** [comment]
@kmdalal Thanks for mentioning the actual fix!

**Comment by oceank** [comment]
With new build command for PLEXIL, "make universalExec plexil-compiler checkpoint", the issue related to CheckpointAdapter is resolved. This is verified when running the autonomy module (tag: v7.0.1) with the Reference1Mission.plx.
